/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class process1 extends javax.swing.JFrame {

    /**
     * Creates new form process1
     */
    public process1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        w = new javax.swing.JButton();
        checkBalanceBtn = new javax.swing.JButton();
        t = new javax.swing.JButton();
        cp = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        rt = new javax.swing.JButton();
        cco = new javax.swing.JButton();
        depositBtn = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("  Welcome.....");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        w.setBackground(new java.awt.Color(204, 204, 255));
        w.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        w.setText("Withdrawal");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });

        checkBalanceBtn.setBackground(new java.awt.Color(204, 204, 255));
        checkBalanceBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checkBalanceBtn.setText("Balance Inquiry");
        checkBalanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceBtnActionPerformed(evt);
            }
        });

        t.setBackground(new java.awt.Color(204, 204, 255));
        t.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        t.setText("Transfer");

        cp.setBackground(new java.awt.Color(204, 204, 255));
        cp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cp.setText("Change Pin");

        pay.setBackground(new java.awt.Color(204, 204, 255));
        pay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pay.setText("Payment");

        rt.setBackground(new java.awt.Color(204, 204, 255));
        rt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rt.setText("Recent Transactions");
        rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtActionPerformed(evt);
            }
        });

        cco.setBackground(new java.awt.Color(204, 204, 255));
        cco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cco.setText("Credit Card Operations");

        depositBtn.setBackground(new java.awt.Color(204, 204, 255));
        depositBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        depositBtn.setText("Deposit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(w, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBalanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(t, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w)
                    .addComponent(pay))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rt)
                    .addComponent(checkBalanceBtn))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cco)
                    .addComponent(t))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp)
                    .addComponent(depositBtn))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        l1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l1.setText("Current Status...");
        l1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exitBtn.setBackground(new java.awt.Color(204, 204, 255));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitBtn.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(387, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 143, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(exitBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 143, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(l1)
                .addGap(18, 18, 18)
                .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(130, 130, 130)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(exitBtn)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        
double balance = 10000.0;
    private void wActionPerformed(java.awt.event.ActionEvent evt) {                                  
        // TODO add your handling code here:
        String input = e.getText();
    try {
        double amount = Double.parseDouble(input);
        if (amount <= 0) {
            l1.setText("Enter a positive amount.");
        } else if (amount > balance) {
            l1.setText("Insufficient balance.");
        } else {
            balance -= amount;
            l1.setText("₹" + amount + " withdrawn. New balance: ₹" + balance);
        }
    } catch (NumberFormatException ex) {
        l1.setText("Invalid amount.");
    }
        
    }                                 

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {
    String input = e.getText();
    try {
        double amount = Double.parseDouble(input);
        if (amount <= 0) {
            l1.setText("Enter a positive amount.");
        } else {
            balance += amount;
            l1.setText("₹" + amount + " deposited. New balance: ₹" + balance);
        }
    } catch (NumberFormatException ex) {
        l1.setText("Invalid amount.");
    }
}

    private void tActionPerformed(java.awt.event.ActionEvent evt) {
    String input = e.getText();
    try {
        double amount = Double.parseDouble(input);
        if (amount <= 0) {
            l1.setText("Enter a valid amount.");
        } else if (amount > balance) {
            l1.setText("Insufficient balance.");
        } else {
            balance -= amount;
            l1.setText("₹" + amount + " transferred successfully.");
        }
    } catch (NumberFormatException ex) {
        l1.setText("Invalid amount.");
    }
}

 private void payActionPerformed(java.awt.event.ActionEvent evt) {
    String input = e.getText();
    try {
        double amount = Double.parseDouble(input);
        if (amount <= 0) {
            l1.setText("Enter a valid payment amount.");
        } else if (amount > balance) {
            l1.setText("Payment failed. Not enough balance.");
        } else {
            balance -= amount;
            l1.setText("Payment of ₹" + amount + " completed.");
        }
    } catch (NumberFormatException ex) {
        l1.setText("Invalid amount.");
    }
}
private void ccoActionPerformed(java.awt.event.ActionEvent evt) {
    l1.setText("Credit card operations are currently unavailable.");
}

   
    
    
    
    
    private void checkBalanceBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:

        l1.setText("Current balance: ₹" + balance);

    }                                               

    private void rtActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        l1.setText("Last 3 transactions: -₹200, +₹1000, -₹500");
    }                                  

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(process1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(process1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(process1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(process1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new process1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cco;
    private javax.swing.JButton checkBalanceBtn;
    private javax.swing.JButton cp;
    private javax.swing.JButton depositBtn;
    private javax.swing.JTextField e;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JButton pay;
    private javax.swing.JButton rt;
    private javax.swing.JButton t;
    private javax.swing.JButton w;
    // End of variables declaration                   
}
